name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SYMBOL_VERSION: "3"
          SHOW_OS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          LOCALE: "False"
          COMMIT_BY_ME: "False"
          COMMIT_MESSAGE: "False"
          SHOW_UPDATED_DATE: "True"
          SHOW_LINES_OF_CODE: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_LANGUAGE: "False"
          SHOW_PROJECTS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          UPDATED_DATE_FORMAT: "%m/%d/%Y %H:%M"
          SHOW_UPDATED_DATE: True